package com.hwaryun.signup.state

data class SignUpState(
    val name: String = "",
    val email: String = "",
    val password: String = "",
    val phoneNumber: String = "",
    val address: String = "",
    val houseNumber: String = "",
    val city: String = "",
    val errorNameMsg: Int = 0,
    val errorEmailMsg: Int = 0,
    val errorPasswordMsg: Int = 0,
    val errorPhoneNumberMsg: Int = 0,
    val errorAddressMsg: Int = 0,
    val errorHouseNumberMsg: Int = 0,
    val errorCityMsg: Int = 0,
    val isPasswordVisible: Boolean = false,
    val isNameError: Boolean = false,
    val isEmailError: Boolean = false,
    val isPasswordError: Boolean = false,
    val isPhoneNumberError: Boolean = false,
    val isAddressError: Boolean = false,
    val isHouseNumberError: Boolean = false,
    val isCityError: Boolean = false,
    val isLoading: Boolean = false,
    val signUp: Any? = null,
    val firstStep: Any? = null,
    val error: String = ""
)
